### PR TITLE
:bug: fix: fix chat item width

### LINKED ISSUE #6643: [Bug] 对话模式，当输入长对话，变成“查看详情”后无法呼出删除菜单
### 📦 部署环境

Docker

### 📦 部署模式

客户端模式(lobe-chat 镜像)

### 📌 软件版本

v1.67.2

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

Image

### 📷 复现步骤

_No response_

### 🚦 期望结果

_No response_

### 📝 补充信息

_No response_

### LINKED ISSUE #6657: [Bug] AI 回复内容中包含表格时，排版出现问题。
### 📦 部署环境

Docker

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

1.67.2

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

如下图圆圈处，输出内容包含表格时，若浏览器窗口不够宽，则菜单选项会超出浏览器。
Image

### 📷 复现步骤

让AI呈现一个任意的表格，然后缩小浏览器宽度。

### 🚦 期望结果

如上图方框处，预留一点空间即可。
或者，可否考虑将这个菜单放在鼠标右键？

### 📝 补充信息

_No response_

### LINKED ISSUE #6759: [Bug] 对话复选框按钮被遮挡
### 📦 部署环境

Docker

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

1.68.3

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

由于搜索引用的内容过多，导致的该聊天对话框的复选框被遮盖，无法操作，如下图所示
Image

### 📷 复现步骤

_No response_

### 🚦 期望结果

可以将这个复选框，换个位置

### 📝 补充信息

_No response_

### LINKED ISSUE #6895: [Bug] 单行内容太长时消息编辑相关的按钮显示不了导致无法管理
### 📦 部署环境

Vercel

### 📦 部署模式

服务端模式(lobe-chat-database 镜像)

### 📌 软件版本

v1.70.2

### 💻 系统环境

Windows

### 🌐 浏览器

Edge

### 🐛 问题描述

大模型单行输出消息太长时，会把显示文字的画布撑太宽，此时该消息的 编辑/复制/创建分支 等功能的按钮显示不了，导致相关功能无法使用。附上一个演示视频

https://github.com/user-attachments/assets/4f909d4a-a98a-4079-9309-363b46aeab4d

### 📷 复现步骤

让大模型输出单行内容较长（视频里也可能是markdown表格里的内容太长？？？）的内容，观察该消息的下方相关功能按钮是否正常显示。

### 🚦 期望结果

即使消息很长，按钮也能显示

### 📝 补充信息

另外：大模型输出表格时，经常都会带有 <br> 标签，但是lobachat现在无法正常渲染该标签进行换行，希望也能支持表格内正常渲染换行。类似需求：https://github.com/lobehub/lobe-chat/issues/5705

> 感谢开发者大佬们的辛勤付出❤️

### PR DESCRIPTION
**Pull request by arvinxx**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

- close https://github.com/lobehub/lobe-chat/issues/6895
- close https://github.com/lobehub/lobe-chat/issues/6759
- close https://github.com/lobehub/lobe-chat/issues/6657
- close https://github.com/lobehub/lobe-chat/issues/6643

### CODE REVIEW

**Comment by canisminor1990** [comment]
👍 @arvinxx
<br>
Thank you for raising your pull request and contributing to our Community
Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
If you encounter any problems, please feel free to connect with us.\
非常感谢您提出拉取请求并为我们的社区做出贡献，请确保您已经遵循了我们的贡献指南，我们会尽快审查它。
如果您遇到任何问题，请随时与我们联系。

**Comment by canisminor1990** [comment]
❤️ Great PR @arvinxx ❤️
<br>
The growth of project is inseparable from user feedback and contribution, thanks for your contribution!\
项目的成长离不开用户反馈和贡献，感谢您的贡献!

File: src/chat/ChatItem/index.tsx [hunk 1]
```diff
@@ -57,6 +57,42 @@ const ChatItem = memo<ChatItemProps>(
...
+      if (!contentRef.current || !containerRef.current) return;
+
+      const observer = new ResizeObserver(() => {
+        if (!contentRef.current || !containerRef.current) return;
+
+        const containerWidth = containerRef.current.clientWidth;
+        const contentWidth = contentRef.current.scrollWidth; // 使用scrollWidth获取实际内容宽度
+
+        // 预留给Actions的最小空间 (根据实际Actions大小调整)
+        const actionsMinWidth = 54;
```
Comment (zhuozhiyongde) [inline src/chat/ChatItem/index.tsx:83]: 留少了吧 xd
